config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"  , registrations: "registrations"}

  get '/:name/dashboard' => 'main#dashboard' ,  :as => :dashboard
  patch '/:name/dashboard' => 'main#dashboard' ,  :as => :dashboard_patch

  

  match '/:name/dashboard/basic' => 'main#basic'  , :as => :basic , via: [:post , :patch]
  

  root 'main#index'

end

app/models/basic.rb
class Basic < ActiveRecord::Base
	validates :full_name , presence: true
	validates :phone , format: {:with => /\A\d{10}\Z/ , message: 'must be number and 10 digits'}
end

app/models/education.rb
class Education < ActiveRecord::Base
end

app/models/exp.rb
class Exp < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
	validates :proj_name , presence: true
end

app/models/skill.rb
class Skill < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable , :omniauthable, :omniauth_providers => [:google_oauth2]
  # devise :omniauthable, :omniauth_providers => [:google_oauth2]
         
   has_one :basic , dependent: :destroy


   has_many :educations ,  dependent: :destroy
   		 accepts_nested_attributes_for :educations, reject_if: proc { |attributes| attributes['degree'].blank? } , allow_destroy: true

   	has_many :projects ,  dependent: :destroy
   		 accepts_nested_attributes_for :projects, allow_destroy: true
# , reject_if: proc { |attributes| attributes['proj_name'].blank? } ,

    has_many :exps ,  dependent: :destroy
       accepts_nested_attributes_for :exps, reject_if: proc { |attributes| attributes['comp_name'].blank? } , allow_destroy: true

    has_many :skills ,  dependent: :destroy
       accepts_nested_attributes_for :skills, reject_if: proc { |attributes| attributes['skill_name'].blank? } , allow_destroy: true

       def self.from_omniauth(access_token)
          data = access_token.info
          user = User.where(:email => data["email"]).first

          # Uncomment the section below if you want users to be created if they don't exist
          unless user
              user = User.create(name: data["name"],
                 email: data["email"],
                 password: Devise.friendly_token[0,20]
              )
          end
          user
      end

  	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index

  	if current_user 
  		redirect_to dashboard_path(current_user.name)
  	end

  end



  def dashboard
  	@var = params[:data]
  	@user = current_user
   
    if @user.basic == nil
      @basic = Basic.new
    else 
      @basic = @user.basic
    end


     if  user_params
     respond_to do |format|
   
      if @user.update(user_params)
        format.js {}
      else
        format.js {}
      end
    end
  end
  	
  end

  def basic
     @user= current_user
     if @user.basic == nil
      
        basic = Basic.new(basic_params) 
        basic.user_id = current_user.id
        respond_to do |format|
          if basic.save
            @basic = basic
            format.js {}
          else
            @basic = basic
            format.js {}
          end
       end

      else 
       respond_to do |format|
        if current_user.basic.update(basic_params)
          @basic = current_user.basic

           format.js {render 'basic'}
        else
          @basic = current_user.basic

           format.js {render 'basic'}
       end
      end
    end



end
 
   

  end










private

def right_user(username) 
  if username != current_user.name
       render '404_page'
       return
    end
  end

def basic_params
    params.require(:basic).permit( :full_name , :email ,:phone ,:linkedin , :essential )
 end

  def user_params
    if params[:user]
  	
        params.require(:user).permit( educations_attributes: [:id, :degree ,:year , :college ,:_destroy] , projects_attributes:[:id , :proj_name , :proj_des,:proj_add ,:_destroy] , exps_attributes:[:id , :comp_name , :comp_location , :role , :duration ,:role_des,:_destroy] , skills_attributes: [:id , :skill_name , :_destroy])
    else 
      return false
    end
  end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		super
		params.require(:user).permit(:name , :email, :password, :password_confirmation)
	end

	def account_update_params
		params.require(:user).permit(:name ,  :email, :password, :password_confirmation)
	end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"])

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/application/_basic_fields.html.slim
div class='nested-fields'
	= f.input :full_name 
	= f.input :email
	= f.input :phone
	= f.input :linkedin 
	= f.input :essential
	
   
   

app/views/application/_education_fields.html.slim
.nested-fields
	=f.input :degree
	=f.input :year
	=f.input :college
	=link_to_remove_association "remove" ,f

app/views/application/_education_update_form.html.slim
= simple_form_for @user , url: {action: 'dashboard' ,:data => 'education'} , remote: true  do |f| 
	h3 Educations
		
	= f.simple_fields_for :educations do |edu|
		= render 'education_fields' , f: edu 
	.links
		= link_to_add_association 'add education', f, :educations

	= f.button :submit 
	




  

app/views/application/_exp_fields.html.slim
div class='nested-fields'
	= f.input :comp_name 
	= f.input :comp_location
	= f.input :role
	= f.input :duration 
	= f.input :role_des
	
   

app/views/application/_exp_update_form.html.slim
= simple_form_for @user , url: {action: 'dashboard' ,:data => 'exp'} , remote: true do |f| 
	h3 Experience
		
	= f.simple_fields_for :exps do |edu|
		= render 'exp_fields' , f: edu 
	.links
		= link_to_add_association 'add education', f, :exps

	= f.button :submit 
	




  

app/views/application/_project_fields.html.slim
.nested-fields
	=f.input :proj_name
	=f.input :proj_des
	=f.input :proj_add
	=link_to_remove_association "remove" ,f

app/views/application/_project_update_form.html.slim
#project_form
	= simple_form_for @user , url: {action: 'dashboard' , :data => 'project' } , remote: true   do |f| 
		h3 Projects
			
		= f.simple_fields_for :projects do |edu|
			= render 'project_fields' , f: edu 
		.links
			= link_to_add_association 'add projects', f, :projects

		= f.button :submit 
	




  

app/views/application/_skill_fields.html.slim
div class='nested-fields'
	= f.input :skill_name
	
   
   

app/views/application/_skill_update_form.html.slim
= simple_form_for @user , url: {action: 'dashboard' , :data => 'skill'}, remote: true do |f| 
	h3 Skills
		
	= f.simple_fields_for :skills do |edu|
		= render 'skill_fields' , f: edu 
	.links
		= link_to_add_association 'add skills', f, :skills

	= f.button :submit 
	



  

app/views/application/_user_basic_create_form.html.slim
= simple_form_for @basic , url: basic_path(data: 'basic')  ,remote: true ,html: { class: 'form-horizontal' } do |f| 
	= f.input :full_name ,class: 'form-control'
	= f.input :email
	= f.input :phone
	= f.input :linkedin 
	= f.input :essential
	= f.button :submit , class: 'btn btn-primary'
		
   
   

app/views/application/_user_basic_edit_form.html.slim
= simple_form_for @basic ,url: user_basic_path do |f| 
	= f.input :full_name 
	= f.input :email
	= f.input :phone
	= f.input :linkedin 
	= f.input :essential
	= f.button :submit 
	
   
   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cvmn</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/basic.js.erb
// $('.outer').empty();
// 	 	$('.outer').append('<%= j render 'user_basic_create_form'%>');
// 	 	

alert('hey');

$('.outer').empty();
$('.outer').append('<%= j render 'user_basic_create_form'%>');

app/views/main/dashboard.html.slim
p dashboard
.well
	hi  =@user.name  

	p
		= link_to 'log out', destroy_user_session_path , method: :delete 

.panel.panel-default.db-panel
	.panel-body.row.panel-in
		.col-md-2
			= link_to "Basic" , dashboard_path(current_user.name , data: "basic") , remote: true , class: 'btn btn-default' , id: 'basic' 
		.col-md-2
			= link_to "Projects" , dashboard_path(current_user.name , data: "project") , remote: true , class: 'btn btn-default' , id: 'project'
		.col-md-2
			= link_to "Educations" , dashboard_path(current_user.name , data: "education") , remote: true , class: 'btn btn-default' 
		.col-md-2
			= link_to "Experience" , dashboard_path(current_user.name , data: "exp") , remote: true , class: 'btn btn-default' 
		.col-md-2
			= link_to "Skills" , dashboard_path(current_user.name , data: "skill") , remote: true , class: 'btn btn-default' 
			


div class='outer well'
		= render 'user_basic_create_form' 
	
	
	
		

div class='alert-box'

app/views/main/dashboard.js.erb
// $(document).ready(function() {
	var variable = "<%=@var%>";
	alert(variable);
	// alert(variable);

	if(variable == 'basic'){
		$('.outer').empty();
	 	$('.outer').append('<%= j render 'user_basic_create_form'%>');
	} else if(variable == 'project'){
		$('.outer').empty();
	 	$('.outer').append('<%= j render 'project_update_form'%>');
	}else if(variable == 'education'){
		$('.outer').empty();
		 $('.outer').append('<%= j render 'education_update_form'%>');
	} else if(variable == 'exp'){
		$('.outer').empty();
	 	$('.outer').append('<%= j render 'exp_update_form'%>');
	}  else if(variable == 'skill'){
		$('.outer').empty();
	 	$('.outer').append('<%= j render 'skill_update_form'%>');
	} 	

	
// });

app/views/main/index.html.slim
.header
	h2 Join us and make an awsome resume for ur self :)...
	=link_to 'Register' , new_user_registration_path, class: 'button'